Add fgenesh tool
usegalaxy-au/galaxy-media-site pull request #128
Opened 2024-06-18 23:37 UTC by AnnaSyme

Need to check button link works ok, and are multiple input file types ok on a single line

2024-06-19 01:08 UTC, neoformit requested changes

2024-06-19 01:08 UTC, neoformit commented on webapp/home/labs/genome/annotation.yml
> +            <code>FGenesH</code> annotates an assembled genome and outputs a GFF3 file. There are several modules that do different things; search for FGENESH in the tool panel to see them. Note: ple
Using markdown again, should be `<a href="~url~">this link</a>`

2024-06-19 01:08 UTC, neoformit commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
I pushed a commit which fixes this - let me know if it's not what you want.

2024-06-19 01:09 UTC, neoformit commented
@AnnaSyme I check the link and made some changes, here's how it looks. Feel free to edit further if necessary:

![image](https://github.com/usegalaxy-au/galaxy-media-site/assets/42562517/a416fd7a-606a-4af3-9f03-0cdf8ac53d12)

2024-06-19 04:49 UTC, AnnaSyme commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
perfect, thank you! @neoformit

2024-06-19 04:53 UTC, merged

2024-06-19 21:56 UTC, neoformit commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
@AnnaSyme I just checked, and `pro`, `cdna`, `dat` do not seem to be Galaxy datatypes? I can see this confusing people if they try to create these data in Galaxy? Maybe this should be:

```yml
- datatypes:
    - fasta
  label: cDNA or protein sequences for [ ... ]
```

Or maybe this should be omitted altogether, if it's specific to the TSI WF? In the *FGENESH
Genome Annotation* tool I can only see these:

```yml
- datatypes:
    - fasta
  label: map known mRNA data to genomic sequence
- datatypes:
    - fasta
  label: map known ESTs to genomic sequence
```

2024-06-20 04:28 UTC, AnnaSyme commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
hmm yes. perhaps simpler just not to mention these files, as they are optional? If a user was going to use them, they would know what they were. If they are following TSI workflows, they would read about these in the How-To guide.

2024-06-20 04:31 UTC, neoformit commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
Yes, if they're optional I'd just leave them out. The idea of listing input data here was to indicate what data the researcher NEEDS in order to run the tool - gets a bit complicated trying to list all possibilities. Shall I remove?

2024-06-20 04:51 UTC, AnnaSyme commented on webapp/home/labs/genome/annotation.yml
> +              - .cdna, .pro, .dat
yes plz remove thanks