Feedback from Proteomics Lab working group
usegalaxy-au/galaxy-media-site pull request #71
Opened 2023-10-23 04:52 UTC by supernord

2023-11-13 00:17 UTC, supernord commented
@neoformit 😄

2023-11-15 20:13 UTC, neoformit requested changes
One comment to address Johan, otherwise this looks good

2023-11-15 20:13 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +            {'datatypes': ['thermo.raw']},
These first three look like they should be one input with three accepted datatypes, not three separate inputs? This implies that MaxQuant requires a `thermo.raw`, `mzMl` AND `mzXML` input to work! And maybe add a label?

2023-11-15 20:13 UTC, neoformit commented
Hey @supernord are you running this locally, I can't remember?

2023-11-15 22:33 UTC, supernord commented
hey @neoformit - I think I've fixed the issue with the datatypes
I'm not running this locally at the moment

2023-11-15 22:56 UTC, neoformit commented
> I'm not running this locally at the moment
Let me know if you want to - it can be useful to preview changes as you make them

2023-11-15 22:58 UTC, supernord commented
Thanks @neoformit 
What is required to run the media site locally?

2023-11-15 23:19 UTC, neoformit commented
https://github.com/usegalaxy-au/galaxy-media-site/wiki/Development#developer-setup 

Short answer - 
```sh
git clone
virtualenv venv
pip install -r requirements.txt
``
`

2023-11-16 01:12 UTC, neoformit requested changes

2023-11-16 01:16 UTC, supernord commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +                'label': 'Thermo raw, mzML, or mzXML files'
Thanks @neoformit - updated to make this clear

2023-11-16 01:27 UTC, neoformit requested changes

2023-11-16 01:27 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +                'label': 'Mass spectrometry data sets: Thermo raw, mzML, or mzXML files'
Sorry, can you delete `: Thermo raw, mzML, or mzXML files` as this is just a repeat of the `datatype` information

2023-11-16 01:32 UTC, neoformit requested changes
Sorry just spotted a bunch of other stuff

2023-11-16 01:32 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/conversion_modification.py
> +                'datatypes': ['thermo.raw', 'mzML', 'mzXML', 'raw', 'wiff', 'wiff.tar', 'agilentbrukeryep.d.tar', 'agilentmasshunter.d.tar', 'brukerbaf.d.tar', 'brukertdf.d.tar', 'watersmasslynx.raw.
This is how it should be done

2023-11-16 01:32 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +                'datatypes': ['mzml'],
This should be `mzMl` to match other instances

2023-11-16 01:32 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +                'datatypes': ['fasta,uniprotxml'],
`['fasta,uniprotxml']` should be two strings, not a string with internal comma

2023-11-16 01:32 UTC, neoformit commented on webapp/home/subdomains/proteomics/content/database_searching.py
> +                'datatypes': ['mzml,mzxml'],
As above on casing (`mzMl`, `mzXML`) and internal comma

2023-11-16 02:55 UTC, supernord commented
Done 😄 
@neoformit

2023-11-16 02:58 UTC, neoformit approved these changes

2023-11-16 04:55 UTC, neoformit commented
Hey @supernord could you please merge against `usegalaxy-au:main`?

2023-11-16 06:02 UTC, merged